### ISSUE TITLE
Compile Warnings 

### ISSUE THREAD

**Issue by astavenga-ucsd** [ucsdCSE110wi16/CSE110M240T8#3]
There are two compile warnings that should be addressed:

Warning:Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for debug as it may be conflicting with the internal version provided by Android.

Warning:Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for release as it may be conflicting with the internal version provided by Android.

**Comment by samueladamsonline** [comment]
Fixed by adding excludes in app module's build.gradle.
