### ISSUE TITLE
Register Screen Enchancements

### ISSUE THREAD

**Issue by darrenbrokeit** [ucsdCSE110wi16/CSE110M240T8#4]
Tried registering - some comments:
- Auto populate email and password fields from login screen if "register" is clicked
- Hide passwords (we discussed this on Friday, just wanted to put it down in writing!)

**Comment by astavenga-ucsd** [comment]
Done in commit 0e22f48

**Comment by darrenbrokeit** [comment]
Thanks for your work Austin, found one more "3 second issue" that should be looked into at some point, where the Confirm Password field shouldn't be populated when info is transferred from log in screen

**Comment by astavenga-ucsd** [comment]
I don't know what I was thinking when I did that, it totally bypasses the point of the user verifying the password. Fixed in f5fd510

**Comment by darrenbrokeit** [comment]
Uno mas: The location needs to be single line.

**Comment by astavenga-ucsd** [comment]
Location is now restricted to a single line. When the user presses the 'enter' the keyboard will be removed and they can press the register button. a2d2b10
