### ISSUE TITLE
When registering for an account, it goes straight to the the "User Account" Page

### ISSUE THREAD

**Issue by darrenbrokeit** [ucsdCSE110wi16/CSE110M240T8#6]
Needs go to the "main page"

**Comment by astavenga-ucsd** [comment]
It is coded to go to the main page. However, if the user clicks on register more than once, this becomes a problem. I still need to look into what would be the best solution, but for now a temporary fix has been made. 1810b49

**Comment by astavenga-ucsd** [comment]
It appears as though my temporary fix works. I have repeatedly tried to move to the user profile page directly from registration and have not been able to.
