### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by darrenbrokeit** [ucsdCSE110wi16/CSE110M240T8#8]
h1. Description Truncate
- On Create, I expect
- On click, the new window should contain: Reviewer Name, Reviewer Location, Star Rating, Full length review

h1. Transition into Product Page
- On submit of sucessful olay, I expect a title, image, and description
- On submit of invalid or non walmart UPC, I expect a toast that says "you're an idiot" (Daniel)
- On submit of no UPC, I expect a message for trying again, or random object
- I expect two buttons that work

h1. Login Page
- Expect to be able to put in valid username / password and to then sign in
- Upon incorrect password, I expect message to say invalid (FOR LATER)

h1. Registration Page
- If I fail to submit all of the fields, I expect it to give me an error
- Unique user (on email) check

**Comment by astavenga-ucsd** [comment]
We need to put these into scenarios using the given-when-then template

**Comment by darrenbrokeit** [comment]
Austin & Daniel added Login Test and Product Info Page Test.

**Comment by darrenbrokeit** [comment]
Darren and Austin added Registration Tests (Pass and Fails)

**Comment by astavenga-ucsd** [comment]
Unit testing has been completed the major aspects of the app have been tested.
